# Default values for training.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: localhost:5000 
  name: training_container
  pullPolicy: IfNotPresent

mountpath:
  trainPath: <absolute-path-of-chart-directory>
  dataPath: <absolute-path-of-chart-directory>/data
  modelPath: <absolute-path-of-chart-directory>/Model-References/PyTorch/computer_vision/segmentation/Unet
  resultsPath: <absolute-path-of-chart-directory>/fold_0