apiVersion: v1
kind: Pod
metadata:
  name: {{ include "onnx-to-ir-optimization.fullname" . }}
  labels:
    {{- include "onnx-to-ir-optimization.labels" . | nindent 4 }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
      imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          
      command: ['mo', '--input_model', '/home/Optimization/onnx_model/unet2d.onnx', '--input_shape', '[1,4,192,160]', '--data_type', 'FP32', '--output_dir', '/home/Optimization/ir_model/FP32']
      env:
        {{- range $key, $val := .Values.env }}
         - name: {{ $key }}
           value: {{ $val | quote}}
        {{- end }}

      volumeMounts:
        - name: onnx-model
          mountPath: /home/Optimization/onnx_model
        - name: ir-model
          mountPath: /home/Optimization/ir_model
  volumes:
    - name: onnx-model
      hostPath:
         path: {{.Values.mountpath.onnxmodelvolume}}
    - name: ir-model
      hostPath:
         path: {{.Values.mountpath.irmodelsvolume}}